### ISSUE TITLE
Forecast File for demand

### ISSUE THREAD

**Issue by hamad-ds** [HumaticsLAB/visuelle2.0-code#1]
Forecast file it is not being able to run on demand forecasting task prolly due to non availability of CrossAttnRNNZero. Is their an update on the way?
python forecast_dl.py --new_product 1 --ckpt_path <ckpt_path>

**Comment by joppichristian** [comment]
Hi Hamad,
thanks for reporting this issue. I just address it and push the updates. 
Please re-try. The CrossAttnRNNZero model import was missing in forecast_dl.py.
