### ISSUE TITLE
Dataset clarification 

### ISSUE THREAD

**Issue by sbs23006** [HumaticsLAB/visuelle2.0-code#10]
Hello there, both discounts and sales have a series of columns named `0, 1, 2...11`.. I've read the paper (https://arxiv.org/pdf/2204.06972v1) but couldn't find any explanation...could you please clarify what those values represent?

**Comment by sbs23006** [comment]
Any clarification on `external_code` would be highly appreciated too (I assumed it's the store code, but I see it also in customer data where the store should be another value, so I'm not sure anymore)

**Comment by sbs23006** [comment]
@joppichristian @geriskenderi

**Comment by geriskenderi** [comment]
Hi,

The values [0,1,...,11] represent the sales time series in the 12-week product lifecycle. The "external_code," on the other hand, is a product_id. Essentially, it serves to recognize a particular product uniquely.

Thanks for downloading and using the dataset :)

I'm marking this as closed.
