### ISSUE TITLE
stfore_preprocessed_test file

### ISSUE THREAD

**Issue by hamad-ds** [HumaticsLAB/visuelle2.0-code#2]
Hi,
I hope this finds you well. As mentioned in the paper published, only two sales(observation window) are needed to forecast the horizon window(ten weeks) for the SO-Fore(2-10). Opposite to this claims the test file is undertaking all 12 weeks of sales data and does not work appropriately with the logic implemented in the code when the horizon sales data is removed from the test file.
It would be highly thankful to you if you can clarify this.

Best,

**Comment by joppichristian** [comment]
Hi,
thanks for your interest in our work. 
The length of the observed window depends on how you set up the problem and frame the sales .https://github.com/HumaticsLAB/visuelle2.0-code/blob/f2c2167430871732aa3a184e52c48e81be367d64/dataset.py#L64 
In this case, we split a 12weeks long series into 10 frames (length=2+1). The frames are then passed to the model that correctly predicts the 10 horizon values in an autoregressive way. https://github.com/HumaticsLAB/visuelle2.0-code/blob/f2c2167430871732aa3a184e52c48e81be367d64/models/CrossAttnRNN.py#L306  If you want to change the horizon-window, you should simply change how to frame the signal and the out_len parameter of the model.

I hope I was clear.

**Comment by hamad-ds** [comment]
Thanks for your reply, I tried to change framing the signal with observation window 2 and horizon window 10. But I get some errors while running the code.
Can you please upload the code files where observation window is 2 and horizon window is 10. (In forecast i want to provide 2 sales and forecast 10 sales "so-fore2-10 problem" for which you reported 32.25 wape).
For so-fore 2-10 i run the forecast with task mode 0 but still it calculates wape for sofore 2-1 problem.
