### ISSUE TITLE
Task_mode 0 problem

### ISSUE THREAD

**Issue by hamad-ds** [HumaticsLAB/visuelle2.0-code#3]
Task_mode 0 is not working, in paper task_mode 0 (observation window is 2 and horizon window is 10) has 32.25 wape, but upon training and forecasting with task mode 0, wape is 23.7.
I tried to change the frame window, but getting errors.
Can you please upload the updated code files that can run task_mode 0 (observation window is 2 and horizon window is 10)

**Comment by geriskenderi** [comment]
Hi,

I think you've got the order wrong, the 2-10 task corresponds to task_mode != 0. If you look at the code, you can see that the autoregressive for loop is located inside the else block. You ran the 2-1 version, for which you get 23.7 wape and that corresponds with the paper.

Try running with task_mode = 1 and let us know what happens

**Comment by hamad-ds** [comment]
@geriskenderi Thanks for the reply, yes i ran with task mode 1 also, but it also forecast for next 1 instead of 10. @joppichristian in another ticket mentioned that in while framing, forecast_horizon should be 10 instead of 1 and out length need to be updated also.
I did that but getting an error "was expecting embedding dimension of 10, but got 1"
Can you please check it on your side.

**Comment by geriskenderi** [comment]
Hi there,

Thanks to your issue we verified a couple of bugs in the code so thanks a lot for that. Now everything should be working smoothly and the model code is also much shorter and more concise. I will be closing this issue as it is fixed, please open another one in case you run into other problems.

p.s: Sorry, I know this took a very long time but it's been a really busy period for myself and my co-authors.
