### ISSUE TITLE
the code does not include KNN model?

### ISSUE THREAD

**Issue by stoneshi-1999** [HumaticsLAB/visuelle2.0-code#5]
this work is awesome🔥🔥🔥, but i didn't find the code of KNN model that mentioned in the paper😭😭😭，hope u can opensource it too, thx a lot🙇‍🙇‍🙇‍

![image](https://user-images.githubusercontent.com/70521393/188914163-5ca29da8-0f6f-4edf-9190-e0746b8a8146.png)
![image](https://user-images.githubusercontent.com/70521393/188914244-bde1cd0e-0e40-48d7-818b-e6688b38502c.png)

**Comment by geriskenderi** [comment]
Hi, thanks for your interest. You can use any kNN implementation, for example from scikit-learn, to implement the different variants. We do not plan on releasing the code for that baseline in the near future.

Thanks again.
