### ISSUE TITLE
How to get the inventory seires？What does the restock mean in the dataset？

### ISSUE THREAD

**Issue by stoneshi-1999** [HumaticsLAB/visuelle2.0-code#6]
Hi there，this dataset is awesome，but I have some quiz，hope you can help me，thx a lot🙇‍

How to get the inventory seires？
![image](https://user-images.githubusercontent.com/70521393/191159745-16d800a5-2cee-4e32-88a4-11e5b5da0992.png)

What does the restock mean in the dataset？
![image](https://user-images.githubusercontent.com/70521393/191288936-8257bf40-cae7-4a14-9a2b-76745ea46f15.png)

**Comment by joppichristian** [comment]
Hi,
thanks for your interest in our paper. 

The restock column in sales.csv corresponds to the total re-stocking products, including the initial stock (the first bench of products sent to stores). On the restock.csv file, you find the re-stocking information in detail. 
The inventory series is computed by subtracting the item sells from the actual stock (last inventory + restock quantity). We know the inventory plot in the figure is wrong, and we have already arranged to address it for a fixed copy of the paper. 

The correct signal is that: 

![image](https://user-images.githubusercontent.com/8223905/191446896-5768c781-f6f6-4803-88a7-2ed7413cf5bd.png)

Thanks!
