### ISSUE TITLE
task_mode =0 refer to SO-fore2-1 or 2-10 ? 

### ISSUE THREAD

**Issue by stoneshi-1999** [HumaticsLAB/visuelle2.0-code#7]
I'm a little bit confused , hope u can answer me, THX!

in README:
![image](https://user-images.githubusercontent.com/70521393/196940391-601a5761-3375-4bf0-97c7-6b2a3e1bad45.png)

in train_dl.py:
![image](https://user-images.githubusercontent.com/70521393/196940925-2b185d40-42c8-47c6-80f9-b080c4f610a5.png)

**Comment by joppichristian** [comment]
Hi @stoneshi-1999,
thanks for raising this issue.
Task mode = 0 means SO-fore 2-1
Task mode = 1 means SO-fore 2-10
We fix the README immediately!
Thanks again!
